detail/urls.py
from django.urls import path
from . import views

app_name="details"

urlpatterns = [
    path("",views.list, name="list"),
    path("qna/",views.qna, name="qna"),
    path("mypage/",views.mypage, name="mypage"),
    path("signup/",views.signup, name="signup"),
    path("<str:not_found>/",views.error, name="error"),
    ]

detail_05/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('details/',include("detail.urls")),
]

detail/models.py
from django.db import models

# Create your models here.

detail/views.py
from django.shortcuts import render

# Create your views here.

def list(request):
    return render(request, "detail/list.html")

def mypage(request):
    return render(request, "detail/mypage.html")
    
def qna(request):
    return render(request, "detail/qna.html")
    
def signup(request):
    return render(request, "detail/signup.html")
    
def error(request,not_found):
    return render(request, "detail/error.html",{"not_found":not_found})

detail/templates/detail/error.html
{% extends "base.html" %}
{% load static %}
{% block bodyblock %}
<div class="d-flex align-items-center justify-content-center"style="height: 350px; width:100%; background-image:url('/static/img/gae6.jpg'); background-size:100%;">
        <h1>{{not_found}}/는 없는 경로입니다.</h1>
</div>

{% endblock %}

detail/templates/detail/list.html
{% extends "base.html" %}
{% load static %}
{% block bodyblock %}
<header class="container col-12">
    <div class="d-flex align-items-center justify-content-center"style="height: 350px; width:100%; background-image:url('/static/img/gae2.jpg'); background-size:100%;">
        <h1>Header</h1>
    </div>
</header>

<footer class="container col-12 fixed-bottom px-5">
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">EUNSOL</a>
      <a class="navbar-brand" href="/details/">상단으로 올라가기</a>
    </nav>
</footer>

{% endblock %}

detail/templates/detail/mypage.html
{% extends "base.html" %}
{% load static %}
{% block bodyblock %}
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card position-fixed" style="width: 18rem;">
      <img src="{% static 'img/gae5.jpg' %}" class="card-img-top rounded-circle"  alt="...">
      <div class="card-body">
        <h5 class="card-title">Name</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Logout</a>
      </div>
    </div>
    </div>
    <div class="col">
    <div class="card">
    <div class="card" style="width: 18rem;">
      <img src="{% static 'img/gae6.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">작성글</h5>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
    <div class="card" style="width: 18rem;">
      <img src="{% static 'img/gae2.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">작성글</h5>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
    <div class="card" style="width: 18rem;">
      <img src="{% static 'img/gae3.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">작성글</h5>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
    <div class="card" style="width: 18rem;">
      <img src="{% static 'img/gae4.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">작성글</h5>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
    </div>
  </div>
  </div>




{% endblock %}

detail/templates/detail/qna.html
{% extends "base.html" %}
{% block bodyblock %}
<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="title">제목</label>
      <input type="text" class="form-control" id="title">
    </div>
    <div class="form-group col-md-6">
      <label for="email">이메일</label>
      <input type="email" class="form-control" id="email">
    </div>
  </div>
  <div class="form-group">
    <label for="content">내용</label>

    <textarea class="form-control" id="content"></textarea>
  </div>
  
  <button type="submit" class="btn btn-primary">Sign in</button>
</form>


{% endblock %}

detail/templates/detail/signup.html
{% extends "base.html" %}
{% load static %}
{% block bodyblock %}
    <div class="container">
      <div class="row">
        <div class="col">
            <img src="{%  static 'img/gae2.jpg' %}"></img>
        </div>
        <div class="col">
            <h1 class="text-center">Sign Up</h1>
            <form>
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
              </div>
              <div class="form-group">
                <label for="Name">Name</label>
                <input type="text" class="form-control" id="Name" placeholder="Enter Name">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword2">Password Confirm</label>
                <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password">
              </div>
              
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
      </div>


    


{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" href="{% static 'img/gae.ico' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
</head>
<body>
        <div class="container col-12">
            <div class="row">
                <div class="container-fluid ">
                    <nav class="navbar sticky-top navbar-light bg-light">
                        <div class="d-flex justify-content-start">
                          <a class="navbar-brand" href="{% url 'details:list' %}">MySite</a>
                          <a class="navbar-brand" href="{% url 'details:qna' %}">Q&A</a>
                        </div>
                        <div class="d-flex justify-content-end">
                          <a class="navbar-brand" href="{% url 'details:mypage' %}">Mypage</a>
                          <a class="navbar-brand" href="{% url 'details:signup' %}">SignUp</a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>

    {% block bodyblock %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
</body>
</html>